# from http://jekyllrb.com/docs/continuous-integration/
sudo: false
language: ruby
cache: bundler

install:
  # Install Jekyll and dependencies
  - bundle install

script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer