# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.email }}, and so on. You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

# edit here to achieve your personal greatness
url: https://meghangutshall.com/
baseurl: ""  # the subpath of your site, e.g. /blog
title: Feral Code Philly
author: Meghan Gutshall
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts from the wild experience of learning to program
avatar: profile.png
email: meghan.gutshall@gmail.com
github: meg-gutshall
twitter: meg_gutshall
linkedin: meghan-gutshall
# stackoverflow: username  # e.g: users/2735833/proton1h1
# disqus: username
# google_analytics: code  # e.g.: UA-69391421-1
header-img: "/static/img/home-bg.png"

# Build settings
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 7
port: 4000
safe: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# needed for travis-ci build
exclude: [vendor]
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]